### ISSUE TITLE
Redirect HTTP Traffic to HTTPS

### ISSUE THREAD

**Issue by jthomerson** [json-schema-org/json-schema-org.github.io#236] opened 2018-09-03 18:45 UTC
Following up on #80 would it no be possible to get http redirecting to https? Maybe even adding HSTS headers?

**Comment by epicfaace** [comment] 2019-08-14 21:37
@handrews is this possible? Additionally, the description on this repo should have the https link, not http.

**Comment by handrews** [comment] 2019-08-14 22:12
@epicfaace IIRC I think it's a github pages limitation?  @Relequestual or @Anthropic might know?  I've been focused on the spec rather than the website.

**Comment by epicfaace** [comment] 2019-08-14 22:17
It's not a limitation (anymore). You need to check the "Enforce HTTPS" checkbox in the Github Pages management console. If the checkbox is not present, the site is probably using an older version of Github Pages and you may need to disable GIthub Pages and then re-enable; then the checkbox will show up. https://help.github.com/en/articles/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

Let me know if you'd like me to help.

**Comment by handrews** [comment] 2019-08-14 22:24
@epicfaace Oh, now I remember- the problem is that the older specs specifically use `http://...` for the meta-schema URIs.  We can't just change that.  New drafts will use `https://...`

I'm pretty sure this is actually a WONTFIX, since we can't selectively enforce it.

**Comment by epicfaace** [comment] 2019-08-14 23:51
> @epicfaace Oh, now I remember- the problem is that the older specs specifically use `http://...` for the meta-schema URIs. We can't just change that. New drafts will use `https://...`

That should be fine -- doing "force HTTPS" on Github pages simply redirects all http:// links to https://

**Comment by handrews** [comment] 2019-08-15 02:24
@epicfaace while *technically* implementations should not automatically retrieve the meta-schemas from the canonical URI, if they do, it should still work and not break by suddenly returning a redirect.

**Comment by Relequestual** [comment] 2019-11-14 13:20
I can't see any reason to NOT do this.
"transparently redirect" is what is claimed.

@handrews Older specs specifically use http as opposed to https, true, but given the redirects are seamless... I don't see it as a problem.
Is there still an objection? Where would this potentially cause a problem?

**Comment by handrews** [comment] 2019-11-14 17:20
> Where would this potentially cause a problem?

I'm sure someone will complain about it but I don't care enough to argue over it.

**Comment by philsturgeon** [comment] 2019-11-15 11:28
Redirecting with proper redirects seems fine to me.

**Comment by handrews** [comment] 2019-11-15 20:00
@philsturgeon @Relequestual as long as y'all deal with the people who complain it's fine with me.

**Comment by Relequestual** [comment] 2019-11-17 20:02
Yup, send them my way.
Same applies for anything you don’t want to deal with =]

**Comment by Relequestual** [comment] 2019-11-17 20:03
Done!

**Comment by Relequestual** [comment] 2021-09-02 08:31
It looks like this got undone at some point: https://github.com/json-schema-org/community/discussions/39
Currently the GitHub UI has disabled the checkbox with a warning.
Investigation needed.

**Comment by jviotti** [comment] 2021-09-03 12:48
@Relequestual What is the warning that GitHub shows?

**Comment by Relequestual** [comment] 2021-09-03 13:33
> Unavailable for your site because your domain is not properly configured to support HTTPS (json-schema.org) — [Troubleshooting custom domains](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors)

Just requires someone to investigate. If you have the time, feel free!

**Comment by jviotti** [comment] 2021-09-05 18:52
According to the docs, some of the DNS records might not be set correctly. I'm not sure what hosting provider is used by JSON Schema, but this is how my personal website (hosted on GitHub Pages) is configured with HTTPS enabled on Namecheap:

<img width="1129" alt="Screen Shot 2021-09-05 at 14 51 47" src="https://user-images.githubusercontent.com/2192773/132138147-96a05715-466d-477f-a7ab-df1a0b43b765.png">

**Comment by karenetheridge** [comment] 2021-09-06 05:10
https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by benjagm** [comment] 2023-10-11 09:45
Closed as completed with the new website.

**Closed** 2023-10-11 09:45 UTC
